### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by ReifiedException** [HanXHX/ansible-php#15]
When running this role as

` - { role: HanXHX.php, php_version: '8.1', php_install_fpm: true }`

I get this error:

`TASK [HanXHX.php : TEMPLATE | Deploy pool configuration] *****************************************************************************************************************************************************************************************************************************************************************************************
fatal: [playground]: FAILED! => {"msg": "'dict object' has no attribute 'hanxhx_php'"}`

The target host is running Debian 11.

**Comment by HanXHX** [comment]
Hi,

Is the file exist `/etc/ansible/facts.d/hanxhx_php.fact`  on the target host?

Best,

Emilien
