### ISSUE TITLE
Can't manage environment variables of php-fpm pool 

### ISSUE THREAD

**Issue by Totooow** [HanXHX/ansible-php#16]
Hi 🙂

I need to pass an environment variable to a custom pool like in [this example from the php manual](https://www.php.net/manual/fr/install.fpm.configuration.php#example-24), (for example `env[TMP] = /tmp`).
Would it be possible to add this feature?

Thanks !

Théo

**Comment by HanXHX** [comment]
Sure.

Feel free to create a PR. I will be happy to add this feature.
